name: ci

on:
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Docker Services
        run: docker compose up -d --build

      - name: Frontend Lint
        run: docker compose exec frontend npm run lint

      - name: Frontend Build
        run: docker compose exec frontend npm run build

      - name: Backend Test
        run: docker compose exec backend npm run test

      - name: Stop Containers
        if: always()
        run: docker compose down
